### ISSUE TITLE
Build fails on Windows because of 2 failing TestOriginLinkFormatter test cases

### ISSUE THREAD

**Issue by cruzel89** [itsallcode/openfasttrace#177]
# Description
When executing `mvn install` on Windows the build fails because of 2 failing TestOriginLinkFormatter test cases.

## Steps to Reproduce
1. Open a CMD or Git Bash in the directory where OFT was cloned to
2. Execute `mvn install`

## Expected behavior
Build finishes successfully

# Environment
- OFT: 2.0.1
- OS: Windows 7 x64
- Java Version: 1.8.0_181
- Maven Version (in case of build problems only): 3.5.4

## Error messages
```
[ERROR] testFormatRegularAbsoluteUnixPath(org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError:

Expected: "<span class=\"origin\"><a href=\"file:///foo/bar/baz\">/foo/bar/baz</a>:1111</span>"
     but: was "<span class=\"origin\">/foo/bar/baz:1111</span>"
        at org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter.assertPathAndLineRenderedToSpan(TestOriginLinkFormatter.java:57)
        at org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter.testFormatRegularAbsoluteUnixPath(TestOriginLinkFormatter.java:85)
```

```
[ERROR] testFormatAbsoluteUnixPathWithSpecialCharacters(org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:

Expected: "<span class=\"origin\"><a href=\"file:///fo%20o/b%C3%A4r/baz\">/fo o/bär/baz</a>:12345678</span>"
     but: was "<span class=\"origin\">/fo o/bär/baz:12345678</span>"
        at org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter.assertPathAndLineRenderedToSpan(TestOriginLinkFormatter.java:57)
        at org.itsallcode.openfasttrace.report.view.html.TestOriginLinkFormatter.testFormatAbsoluteUnixPathWithSpecialCharacters(TestOriginLinkFormatter.java:92)
```

**Comment by cruzel89** [comment]
Result of my first analysis:

The root cause for both failing tests is that `realPath.isAbsolute()` in `OriginLinkFormatter.java` evaluates to `false`:
```java
    private static URI convertPathWithoutProtocolToUri(final String path)
    {
        final Path realPath = Paths.get(unWindowsify(path));
        if (realPath.isAbsolute())
        {
            return realPath.toUri();
        }
        return null;
    }

    private static String unWindowsify(final String path)
    {
        return path.replaceAll("([A-Z]:)", "/$1").replaceAll("\\\\", "/");
    }
```

This implementation looks very UNIX-specific.
@redcatbear: Was this implemented UNIX-specific on purpose? Because in this case it does not make sense that this test cases are executed during a build on WIN.
